# docker compose -f docker-compose.build.yml up --build
services:
  skysend:
    build: .
    container_name: skysend-test
    restart: always
    expose:
      - "3000"
    environment:
      - BASE_URL=https://123123.ngrok-free.app
      - DATA_DIR=/data
      - UPLOADS_DIR=/uploads
      - FILE_MAX_SIZE=10GB
      - FILE_MAX_FILES_PER_UPLOAD=10
      - FILE_EXPIRE_OPTIONS_SEC=300,3600,3434
      - FILE_DEFAULT_EXPIRE_SEC=3600
      - FILE_DOWNLOAD_OPTIONS=10,50,1000
      - FILE_DEFAULT_DOWNLOAD=50
      - FILE_UPLOAD_QUOTA_BYTES=10GB
      - FILE_UPLOAD_CONCURRENT_CHUNKS=10
    # - FILE_UPLOAD_SPEED_LIMIT=50MB
    #  - PUID=${PUID:-1001}
    #  - PGID=${PGID:-1001}
      - CUSTOM_TITLE=SkySend Build
      - CUSTOM_COLOR=ff5f5a
    # Drop the file into ./test/data/branding/ and reference it by path.
    #  - CUSTOM_LOGO=/branding/logo.svg
      #CUSTOM_LOGO=
      - CUSTOM_PRIVACY=https://skysend.app
      - CUSTOM_LEGAL=https://skysend.app
      - CUSTOM_LINK_URL=https://skysend.app
      - CUSTOM_LINK_NAME=Build
      - TRUST_PROXY=true
    volumes:
      - ./test/data:/data
      - ./test/uploads:/uploads

  caddy:
    image: caddy:2-alpine
    container_name: skysend-proxy
    restart: always
    ports:
    # - "443:443"
      - "80:80"
    # command: caddy reverse-proxy --from localhost --to skysend:3000 (HTTPS)
    command: caddy reverse-proxy --from :80 --to skysend:3000 #(HTTP)
    depends_on:
      - skysend
